swagger: '2.0'
info:
  title: calis-api
  description: |-
    This is The Official Private API for **Calis - Aplikasi Belajar Baca, Tulis, Hitung** mobile app. You need to provide a Google **id_token** in the **Authorization** bearer in order to call this API. Example:
    **curl -X GET "https://host/v1/whoami" -H "accept: application/json" -H "Authorization: Bearer your_id_token"**
    
    Any Google **id_token** that are not from our Official Mobile App will be invalid. For Bangkit team, you can use [this](https://authecho-vws3d6ozda-et.a.run.app/) to get valid **id_token** (this will be deleted when the app released to public).
  
  version: 1.0.0
  
host: gateway-calis-46kwzo0x.an.gateway.dev
basePath: /v1

schemes:
  - https
  - http
produces:
  - application/json
  
tags:
  - name: auth
    description: Everything about auth
  - name: profile
    description: Everything about user profile
  - name: admin
    description: Endpoint for admin only
  - name: lesson
    description: Endpoint related to lesson
  - name: user-learning
    description: Endpoint related to user learning progress

securityDefinitions:
  ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /whoami:
    get:
      tags:
        - auth
      summary: Auth echo, return your token information
      consumes:
      - application/json
      operationId: authecho
      x-google-backend:
        address:  https://whoami-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: Successful response
      security:
      - ApiKeyAuth: []
  
  /login:
    get:
      tags:
        - auth
      summary: Endpoint for login and/or register
      consumes:
      - application/json
      operationId: login
      x-google-backend:
        address:  https://login-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: User successfully login/register
          schema:
            type: object
            properties:
              createdAt:
                type: string
                description: datetime when was user first login/register
              email:
                type: string
                description: the user email
              children:
                type: object
                description: Related children for this user
                properties:
                  random_uuid_value:
                    type: object
                    properties:
                      yearOfBirth:
                        type: integer
                        description: the year when child was born to suffer
                      createdAt:
                        type: string
                        description: when this children added
                      photoUrl:
                        type: string
                        description: url of the children profile pict
                      childName:
                        type: string

        '400':
          description: Invalid request
          schema: 
            type: object
            properties:
              error:
                type: string
                description: the error message  
      security:
      - ApiKeyAuth: []      

  /addChildren:
    post:
      tags:
        - profile
      summary: add children to user
      consumes:
      - application/json
      operationId: addChildren
      x-google-backend:
        address:  https://addchildren-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              childAge:
                type: integer
                description: children age
              childName:
                type: string
                description: children name

      responses:
        '200':
          description: Successful response
          schema:
                type: object
                description: newly created children object
                properties:
                  random_uuid_value:
                    type: object
                    properties:
                      yearOfBirth:
                        type: integer
                        description: the year when child was born to suffer
                      createdAt:
                        type: string
                        description: when this children added
                      photoUrl:
                        type: string
                        description: url of the children profile pict
                      childName:
                        type: string
      security:
      - ApiKeyAuth: []

  /insertLessons:
    post:
      tags:
        - admin
        - lesson
      summary: insert multiple lessons to database
      consumes:
        - application/json
      operationId: insertLessons
      x-google-backend:
        address:  https://insertlessons-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: body
          description: example https://github.com/Calis-Top-10/Soal/blob/main/soal/soal_baca.jsonc
          schema:
            type: object
            properties:
              lessons:
                type: array
                items:
                  type: object
                  properties:
                    lessonType:
                      type: string
                    lessonLevel:
                      type: integer
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          question:
                            type: string
                          answer:
                            type: array
                            items:
                              type: string
                        additionalProperties:
                          type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              message:
                type: string
              lessonIds:
                type: object
                properties:
                  lessonId1:
                    type: integer
                  lessonId2:
                    type: integer

      security:
        - ApiKeyAuth: []

  /getLessonsByType:
    get:
      tags:
        - lesson
      summary: get lessons by type
      consumes:
        - application/json
      operationId: getLessonsByType
      x-google-backend:
        address:  https://getlessonsbytype-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: lessonType
          type: string
          description: lesson type (baca, tulis, hitung)
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lessons:
                type: array
                items:
                  type: object
                  properties:
                    lessonId:
                      type: string
                    lessonType:
                      type: string
                    lessonLevel:
                      type: integer
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          question:
                            type: string
                          answer:
                            type: array
                            items:
                              type: string
                        additionalProperties:
                          type: string
      security:
        - ApiKeyAuth: []

  /updateUserLearning:
    post:
      tags:
        - user-learning
      summary: update user learning progress
      consumes:
        - application/json
      operationId: updateUserLearning
      x-google-backend:
        address:  https://updateuserlearning-vws3d6ozda-et.a.run.app
      parameters:
      - name: body
        in: body
        description: Request payload
        required: true
        schema:
          type: object
          properties:
            childId:
              type: string
              format: uuid
              example: a48db6a1-8cd7-4f25-9df4-d4b6e7bf5674
            lessonId:
              type: string
              format: uuid
              example: 04fb20c5-6e65-474f-805c-cb5d0e104da8
            timestamp:
              type: string
              format: date
              example: 05/06/2023
            attempts:
              type: array
              items:
                type: object
                properties:
                  questionId:
                    type: string
                    format: uuid
                  isCorrect:
                    type: boolean
              example:
                - questionId: 4dd53e83-fdeb-4d2b-ab38-f10520022e88
                  isCorrect: false
                - questionId: 388e837e-1c10-4d30-aaad-8ff039c7fe5f
                  isCorrect: true
                - questionId: d4e8216d-a9c4-4bc5-8824-64aff3c74312
                  isCorrect: false
                - questionId: 3f5e775f-fa0a-4775-8ec5-6db33822b3c2
                  isCorrect: true
                - questionId: 3dd7e44f-d83f-4b0d-8c7a-349db631596e
                  isCorrect: true

      responses:
        200:
          description: success
          schema: 
            type: object
            properties:
              message:
                type: string
      security:
        - ApiKeyAuth: []

  /userReport:
    get:
      tags:
        - user-learning
      summary: report learning
      consumes:
        - application/json
      operationId: userReport
      x-google-backend:
        address:  https://userreport-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: childId
          type: string
          format: uuid

      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              email:
                type: string
                example: c169dsx2787@bangkit.academy
              childId:
                type: string
                format: uuid
                example: c279c01c-5cb7-4b04-aefb-4bb9e05b143a
              tag:
                type: array
                items:
                  type: string
                example:
                  - [baca_mu, 0]
                  - [baca_ba, -2]
                  - [baca_ku, -2]
                  - [baca_bu, -2]
              learningProgress:
                type: object
                properties:
                  monday:
                    type: boolean
                    example: true
                  tuesday:
                    type: boolean
                    example: false
                  wednesday:
                    type: boolean
                    example: true
                  thursday:
                    type: boolean
                    example: false
                  friday:
                    type: boolean
                    example: false
                  saturday:
                    type: boolean
                    example: false
                  sunday:
                    type: boolean
                    example: false
      security:
        - ApiKeyAuth: []
          
  /personalLesson:
    get:
      summary: get personal lesson for child
      operationId: personalLesson
      tags:
        - lesson
      x-google-backend:
        address:  https://personallesson-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: childId
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              lessonId:
                type: string
                example: p_20230607161435.529889
              lessonType:
                type: string
                example: personal
              questions:
                type: array
                items:
                  type: object
                  properties:
                    questionId:
                      type: string
                      format: uuid
                    questionDetails:
                      type: object
                      properties:
                        answer:
                          type: array
                          items:
                            type: string
                        feedback_img:
                          type: string
                          example: "<path ke gambar buku>"
                        question:
                          type: string
                      required:
                        - answer
                        - feedback_img
                        - question
                    questionType:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
                example:
                  - questionId: d4e8216d-a9c4-4bc5-8824-64aff3c74312
                    questionDetails:
                      answer: [buku]
                      feedback_img: "<path ke gambar buku>"
                      question: buku
                    questionType: baca_input_suara
                    tags: [baca_bu, baca_ku, baca_kata_dasar]
                  - questionId: d4e8216d-a9c4-4bc5-8824-64aff3c74312
                    questionDetails:
                      answer: [buku]
                      feedback_img: "<path ke gambar buku>"
                      question: buku
                    questionType: baca_input_suara
                    tags: [baca_bu, baca_ku, baca_kata_dasar]
      security:
      - ApiKeyAuth: []


  /updateChild:
    post:
      tags:
        - profile
      summary: edit child profile
      consumes:
      - application/json
      operationId: updateChild
      x-google-backend:
        address:  https://updatechild-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              childId:
                type: string
                format: uuid
                description: child id
              childAge:
                type: integer
                description: children age
              childName:
                type: string
                description: children name

      responses:
        '200':
          description: Successful response
          schema:
                type: object
                description: newly created children object
                properties:
                  message:
                    type: string
                    example: "uuid edited"
      security:
      - ApiKeyAuth: []
        
  /deleteChild:
      post:
        tags:
          - profile
        summary: delete child profile
        consumes:
        - application/json
        operationId: deleteChild
        x-google-backend:
          address:  https://deletechild-vws3d6ozda-et.a.run.app
        parameters:
          - in: body
            name: body
            schema:
              type: object
              properties:
                childId:
                  type: string
                  format: uuid
                  description: child id

        responses:
          '200':
            description: Successful response
            schema:
                  type: object
                  description: meaw meaw
                  properties:
                    message:
                      type: string
                      example: "uuid deleted"
        security:
        - ApiKeyAuth: []
    
  /getLesson:
    get:
      summary: get lesson for child
      operationId: getLesson
      tags:
        - lesson
      x-google-backend:
        address:  https://getlesson-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: lessonId
          type: string
          format: uuid
      responses:
        200:
          description: OK
          
  /getQuestion:
    get:
      summary: get qeustion
      operationId: getQuestion
      tags:
        - lesson
      x-google-backend:
        address:  https://getquestion-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: questionId
          type: string
          format: uuid
      responses:
        200:
          description: OK
          

  /getChildById:
    get:
      summary: get child by id (you must own this child)
      operationId: getChildById
      tags:
        - profile
      x-google-backend:
        address: https://getchildbyid-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: childId
          type: string
          format: uuid
      responses:
        200:
          description: child object
      security:
        - ApiKeyAuth: []

  /docs:
    get:
      summary: Endpoint for this -_-
      operationId: doc
      x-google-backend:
        address:  https://docs-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: Successful response


