swagger: '2.0'
info:
  title: calis-api
  description: |-
    This is API for calis mobile app. **make sure to provide authorization heder**
  version: 1.0.0
  
host: gateway-calis-46kwzo0x.an.gateway.dev
basePath: /v1

schemes:
  - http
  - https
produces:
  - application/json
  
tags:
  - name: auth
    description: Everything about auth
  - name: profile
    description: Everything about user profile
  - name: admin
    description: Endpoint for admin only
  - name: lesson
    description: Endpoint related to lesson

securityDefinitions:
  ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /whoami:
    get:
      tags:
        - auth
      summary: Auth echo
      consumes:
      - application/json
      operationId: authecho
      x-google-backend:
        address:  https://whoami-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: Successful response
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  
  /login:
    get:
      tags:
        - auth
      summary: Endpoint for login and/or register
      consumes:
      - application/json
      operationId: login
      x-google-backend:
        address:  https://login-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: User successfully login/register
          schema:
            type: object
            properties:
              createdAt:
                type: string
                description: datetime when was user first login/register
              email:
                type: string
                description: the user email
              children:
                type: object
                description: Related children for this user
                properties:
                  random_uuid_value:
                    type: object
                    properties:
                      yearOfBirth:
                        type: integer
                        description: the year when child was born to suffer
                      createdAt:
                        type: string
                        description: when this children added
                      photoUrl:
                        type: string
                        description: url of the children profile pict
                      childName:
                        type: string

        '400':
          description: Invalid request
          schema: 
            type: object
            properties:
              error:
                type: string
                description: the error message  
      security:
      - ApiKeyAuth: []      

  /addChildren:
    post:
      tags:
        - profile
      summary: add children to user
      consumes:
      - application/json
      operationId: addChildren
      x-google-backend:
        address:  https://addchildren-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              childAge:
                type: integer
                description: children age
              childName:
                type: string
                description: children name

      responses:
        '200':
          description: Successful response
          schema:
                type: object
                description: newly created children object
                properties:
                  random_uuid_value:
                    type: object
                    properties:
                      yearOfBirth:
                        type: integer
                        description: the year when child was born to suffer
                      createdAt:
                        type: string
                        description: when this children added
                      photoUrl:
                        type: string
                        description: url of the children profile pict
                      childName:
                        type: string
      security:
      - ApiKeyAuth: []

  /insertLessons:
    post:
      tags:
        - admin
        - lesson
      summary: insert multiple lessons to database
      consumes:
        - application/json
      operationId: insertLessons
      x-google-backend:
        address:  https://insertlessons-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: body
          description: example https://github.com/Calis-Top-10/Soal/blob/main/soal/soal_baca.jsonc
          schema:
            type: object
            properties:
              lessons:
                type: array
                items:
                  type: object
                  properties:
                    lessonType:
                      type: string
                    lessonLevel:
                      type: integer
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          question:
                            type: string
                          answer:
                            type: array
                            items:
                              type: string
                        additionalProperties:
                          type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              message:
                type: string
              lessonIds:
                type: object
                properties:
                  lessonId1:
                    type: integer
                  lessonId2:
                    type: integer

      security:
        - ApiKeyAuth: []

  /getLessonsByType:
    get:
      tags:
        - lesson
      summary: get lessons by type
      consumes:
        - application/json
      operationId: getLessonsByType
      x-google-backend:
        address:  https://getlessonsbytype-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: lessonType
          type: string
          description: lesson type
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lessons:
                type: array
                items:
                  type: object
                  properties:
                    lessonId:
                      type: string
                    lessonType:
                      type: string
                    lessonLevel:
                      type: integer
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          question:
                            type: string
                          answer:
                            type: array
                            items:
                              type: string
                        additionalProperties:
                          type: string
      security:
        - ApiKeyAuth: []

  /getLearningData:
    post:
      tags:
        - learning progress
      summary: get learning progress (not ready)
      consumes:
        - application/json
      operationId: getLearningData
      x-google-backend:
        address:  https://getLearningData-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: learningData
          type: string
          description: learning progress
      responses:
        200:
          description: success
          schema: 
            type: object
            properties:
              lesson_id:
                type: string
              timestamp:
                type: string
              attempts:
                type: object
                properties:
                  timestamp:
                    type: string
                  questionId:
                    type: string
                  isCorrect:
                    type: boolean
      security:
        - ApiKeyAuth: []

  /userReport:
    post:
      tags:
        - user report learning
      summary: report learning
      consumes:
        - application/json
      operationId: userReport
      x-google-backend:
        address:  https://userReport-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: reportLearning
          type: string
          description: user report learning 
          schema:
            type: object
            properties:
                email:
                  type: string
                childId:
                  type: string
                tag:
                  type: string
                learningProgress:
                  weekly learning:
                    type: array
                    properties:
                      senin:
                        type: boolean
                      selasa:
                        type: boolean
                      rabu:
                        type: boolean
                      kamis:
                        type: boolean
                      jumat:
                        type: boolean
                      sabtu:
                        type: boolean
                      minggu:
                        type: boolean
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              email:
                type: string
              childId:
                type: string
              tag:
                type: string 
              learningprogress:
                type: object
                properties:
                  senin:
                    type: boolean
                  selasa:
                    type: boolean
                  rabu:
                    type: boolean
                  kamis:
                    type: boolean
                  jumat:
                    type: boolean
                  sabtu:
                    type: boolean
                  minggu:
                    type: boolean
      security:
        - ApiKeyAuth: []

  /docs:
    get:
      summary: Endpoint for this -_-
      operationId: doc
      x-google-backend:
        address:  https://docs-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: Successful response

