swagger: '2.0'
info:
  title: calis-api
  description: |-
    This is API for calis mobile app. **make sure to provide authorization header**. For testing, you can get it here: [auth echo](https://authecho-vws3d6ozda-et.a.run.app/)
  version: 1.0.0
  
host: gateway-calis-46kwzo0x.an.gateway.dev
basePath: /v1

schemes:
  - https
  - http
produces:
  - application/json
  
tags:
  - name: auth
    description: Everything about auth
  - name: profile
    description: Everything about user profile
  - name: admin
    description: Endpoint for admin only
  - name: lesson
    description: Endpoint related to lesson

securityDefinitions:
  ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /whoami:
    get:
      tags:
        - auth
      summary: Auth echo
      consumes:
      - application/json
      operationId: authecho
      x-google-backend:
        address:  https://whoami-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: Successful response
          schema:
            type: string
      security:
      - ApiKeyAuth: []
  
  /login:
    get:
      tags:
        - auth
      summary: Endpoint for login and/or register
      consumes:
      - application/json
      operationId: login
      x-google-backend:
        address:  https://login-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: User successfully login/register
          schema:
            type: object
            properties:
              createdAt:
                type: string
                description: datetime when was user first login/register
              email:
                type: string
                description: the user email
              children:
                type: object
                description: Related children for this user
                properties:
                  random_uuid_value:
                    type: object
                    properties:
                      yearOfBirth:
                        type: integer
                        description: the year when child was born to suffer
                      createdAt:
                        type: string
                        description: when this children added
                      photoUrl:
                        type: string
                        description: url of the children profile pict
                      childName:
                        type: string

        '400':
          description: Invalid request
          schema: 
            type: object
            properties:
              error:
                type: string
                description: the error message  
      security:
      - ApiKeyAuth: []      

  /addChildren:
    post:
      tags:
        - profile
      summary: add children to user
      consumes:
      - application/json
      operationId: addChildren
      x-google-backend:
        address:  https://addchildren-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              childAge:
                type: integer
                description: children age
              childName:
                type: string
                description: children name

      responses:
        '200':
          description: Successful response
          schema:
                type: object
                description: newly created children object
                properties:
                  random_uuid_value:
                    type: object
                    properties:
                      yearOfBirth:
                        type: integer
                        description: the year when child was born to suffer
                      createdAt:
                        type: string
                        description: when this children added
                      photoUrl:
                        type: string
                        description: url of the children profile pict
                      childName:
                        type: string
      security:
      - ApiKeyAuth: []

  /insertLessons:
    post:
      tags:
        - admin
        - lesson
      summary: insert multiple lessons to database
      consumes:
        - application/json
      operationId: insertLessons
      x-google-backend:
        address:  https://insertlessons-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: body
          description: example https://github.com/Calis-Top-10/Soal/blob/main/soal/soal_baca.jsonc
          schema:
            type: object
            properties:
              lessons:
                type: array
                items:
                  type: object
                  properties:
                    lessonType:
                      type: string
                    lessonLevel:
                      type: integer
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          question:
                            type: string
                          answer:
                            type: array
                            items:
                              type: string
                        additionalProperties:
                          type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              message:
                type: string
              lessonIds:
                type: object
                properties:
                  lessonId1:
                    type: integer
                  lessonId2:
                    type: integer

      security:
        - ApiKeyAuth: []

  /getLessonsByType:
    get:
      tags:
        - lesson
      summary: get lessons by type
      consumes:
        - application/json
      operationId: getLessonsByType
      x-google-backend:
        address:  https://getlessonsbytype-vws3d6ozda-et.a.run.app
      parameters:
        - in: query
          name: lessonType
          type: string
          description: lesson type
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lessons:
                type: array
                items:
                  type: object
                  properties:
                    lessonId:
                      type: string
                    lessonType:
                      type: string
                    lessonLevel:
                      type: integer
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          question:
                            type: string
                          answer:
                            type: array
                            items:
                              type: string
                        additionalProperties:
                          type: string
      security:
        - ApiKeyAuth: []

  /updateUserLearning:
    post:
      tags:
        - learning progress
      summary: update user learning progress
      consumes:
        - application/json
      operationId: updateUserLearning
      x-google-backend:
        address:  https://updateuserlearning-vws3d6ozda-et.a.run.app
      parameters:
      - name: body
        in: body
        description: Request payload
        required: true
        schema:
          type: object
          properties:
            childId:
              type: string
              format: uuid
              example: a48db6a1-8cd7-4f25-9df4-d4b6e7bf5674
            lessonId:
              type: string
              format: uuid
              example: 04fb20c5-6e65-474f-805c-cb5d0e104da8
            timestamp:
              type: string
              format: date
              example: 05/06/2023
            attempts:
              type: array
              items:
                type: object
                properties:
                  questionId:
                    type: string
                    format: uuid
                  isCorrect:
                    type: boolean
              example:
                - questionId: 4dd53e83-fdeb-4d2b-ab38-f10520022e88
                  isCorrect: false
                - questionId: 388e837e-1c10-4d30-aaad-8ff039c7fe5f
                  isCorrect: true
                - questionId: d4e8216d-a9c4-4bc5-8824-64aff3c74312
                  isCorrect: false
                - questionId: 3f5e775f-fa0a-4775-8ec5-6db33822b3c2
                  isCorrect: true
                - questionId: 3dd7e44f-d83f-4b0d-8c7a-349db631596e
                  isCorrect: true

      responses:
        200:
          description: success
          schema: 
            type: object
            properties:
              message:
                type: string
      security:
        - ApiKeyAuth: []

  /userReport:
    post:
      tags:
        - user report learning
      summary: report learning
      consumes:
        - application/json
      operationId: userReport
      x-google-backend:
        address:  https://userreport-vws3d6ozda-et.a.run.app
      parameters:
        - in: body
          name: reportLearning
          description: user report learning 
          schema:
            type: object
            properties:
                email:
                  type: string
                childId:
                  type: string
                tag:
                  type: string

      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              email:
                type: string
              childId:
                type: string
              tag:
                type: string 
              learningprogress:
                type: object
                properties:
                  senin:
                    type: boolean
                  selasa:
                    type: boolean
                  rabu:
                    type: boolean
                  kamis:
                    type: boolean
                  jumat:
                    type: boolean
                  sabtu:
                    type: boolean
                  minggu:
                    type: boolean
      security:
        - ApiKeyAuth: []

  /docs:
    get:
      summary: Endpoint for this -_-
      operationId: doc
      x-google-backend:
        address:  https://docs-vws3d6ozda-et.a.run.app
      responses:
        '200':
          description: Successful response

